language: android

git:
    depth: 3

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.3
    - android-24
    - extra-android-support
    - extra-android-m2repository

before_install:
 - chmod +x gradlew

script:
  - ./gradlew clean assembleDebug